ARDUINO_LIBS = Grove_LCD_RGB_Backlight x10rf Grove_Temper_Humidity_TH02 Wire        
BOARD_TAG    = uno
MONITOR_PORT = /dev/ttyACM0
# ARDUINO_CORE_PATH = /home/developer/apps/arduino/hardware/arduino/avr/cores/arduino
# ARDUINO_VAR_PATH = /home/developer/apps/arduino/hardware/arduino/avr/variants
# BOARDS_TXT = /home/developer/apps/arduino/hardware/arduino/avr/boards.txt
# BOOTLOADER_PARENT = /home/developer/apps/arduino/hardware/arduino/avr/bootloaders 
# USER_LIB_PATH = /home/developer/apps/arduino/hardware/arduino/avr/libraries
include /home/developer/apps/Arduino-Makefile/Arduino.mk


