ARDUINO_LIBS = Grove_LCD_RGB_Backlight x10rf Wire Grove_Temper_Humidity_TH02 RfxFruitProtocol SensorTypes
BOARD_TAG    = uno
MONITOR_PORT = /dev/ttyACM0
USER_LIB_PATH = ../

include /home/developer/apps/Arduino-Makefile/Arduino.mk
